metadata:
- description: "\n            This ruleset gives hints to migrate config components
    to Quarkus extension\n        "
  dependencies:
    addon:
    - id: org.jboss.windup.rules,windup-rules-javaee,3.0.0.Final
    - id: org.jboss.windup.rules,windup-rules-java,3.0.0.Final
    - id: org.jboss.windup.rules,windup-rules-xml,3.0.0.Final
  sourceTechnology:
  - id: config
  targetTechnology:
  - id: quarkus
rules:
  rule:
  - when:
      project:
      - artifact:
          groupId: io.smallrye.config
          artifactId: smallrye-config-source-yaml
    perform:
      iteration:
      - hint:
        - message: "\n                            Replace the `io.smallrye.config:smallrye-config-source-yaml`
            dependency with the Quarkus dependency `io.quarkus:quarkus-config-yaml`
            \ \n                            Further information in the link below.\n
            \                       "
          link:
          - value: ""
            title: Quarkus - Guide
            href: https://quarkus.io/guides/config#yaml
          title: Replace the 'smallrye-config-source-yaml' dependency with Quarkus
            'quarkus-config-yaml' extension
          category-id: mandatory
          effort: 1
        over: default
  - when:
      dependency:
      - groupId: io.smallrye.config
        artifactId: smallrye-config-source-yaml
    perform:
      hint:
      - message: "\n                        Replace the `io.smallrye.config:smallrye-config-source-yaml`
          dependency with the Quarkus dependency `io.quarkus:quarkus-config-yaml`
          \ \n                        Further information in the link below.\n                    "
        link:
        - value: ""
          title: Quarkus - Guide
          href: https://quarkus.io/guides/config#yaml
        title: Replace the 'smallrye-config-source-yaml' dependency with Quarkus 'quarkus-config-yaml'
          extension
        category-id: mandatory
        effort: 1
sourceFile: http://github.com/windup/windup-rulesets/tree/master/rules/rules-generated/quarkus/config/config-to-quarkus.windup.xml
